import { config } from '../config';
import path from 'path';
import swaggerJsdoc from 'swagger-jsdoc';

const fileExt = __filename.split('.').at(-1);

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Froggy Jump API',
      version: '1.0.0',
      description: 'API documentation generated by JSDoc and Swagger',
    },
    servers: [
      {
        url: `${config.telegram.twaUrl.split('/').slice(0, 3).join('/')}/api`,
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description:
            'Enter the hash from the Telegram Web App (mini-app) in this field.',
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: [
    path.join(__dirname, `./api-docs.${fileExt}`),
    path.join(__dirname, `../api/**/*.routes.${fileExt}`),
  ],
};

export const swaggerSpec = swaggerJsdoc(options);
