name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region us-east-1 --profile froggy_slava | docker login --username AWS --password-stdin 730335660946.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build, tag, and push Docker image
      run: |
        docker build -t froggy-api .
        docker tag froggy-api:latest 730335660946.dkr.ecr.us-east-1.amazonaws.com/froggy-api:latest
        docker push 730335660946.dkr.ecr.us-east-1.amazonaws.com/froggy-api:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster FroggyClaster --service FroggyService --force-new-deployment
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}